import re
import unittest
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]


class DashboardStaticContractTests(unittest.TestCase):
    def test_service_settings_use_active_provider_without_linux_facing_launchd_fallback(self):
        script = (ROOT / "src" / "dashboard" / "app" / "static" / "js" / "app.js").read_text(encoding="utf-8")
        self.assertIn("status, runtime state, and definition alignment come from the active service manager", script)
        self.assertIn("if (provider) systemTimer.provider = provider", script)
        self.assertNotIn("provider || 'launchd'", script)

    def test_dashboard_mobile_shell_prevents_sidebar_squeeze(self):
        html = (ROOT / "src" / "dashboard" / "app" / "static" / "index.html").read_text(encoding="utf-8")
        css = (ROOT / "src" / "dashboard" / "app" / "static" / "css" / "style.css").read_text(encoding="utf-8")
        script = (ROOT / "src" / "dashboard" / "app" / "static" / "js" / "app.js").read_text(encoding="utf-8")
        self.assertIn('class="mobile-bottom-nav"', html)
        self.assertIn('data-mobile-page="foundation-ops"', html)
        self.assertIn('data-mobile-page="rag-search"', html)
        self.assertIn('data-mobile-utility', html)
        self.assertIn('data-i18n-aria-label="mobileMore"', html)
        self.assertIn('data-mobile-action="settings"', script)
        self.assertIn('function openMobileUtilities()', script)
        self.assertIn('function dashboardModalGenerationIsCurrent(generation)', script)
        self.assertIn('dashboardModalGenerationIsCurrent(modalGeneration)', script)
        self.assertIn(".mobile-bottom-nav", css)
        self.assertIn(".mobile-nav-item", css)
        self.assertIn("grid-template-columns: repeat(6, minmax(0, 1fr))", css)
        self.assertIn("setMobileNavActive(id)", script)
        self.assertIn("function setMobileNavActive(id)", script)
        self.assertIn("item.dataset.mobilePage === id", script)
        self.assertIn("@media (max-width: 720px)", css)
        mobile_shell = css.split("@media (max-width: 720px)", 1)[1].split("@media", 1)[0]
        self.assertIn(".sidebar { display: none; }", mobile_shell)
        self.assertIn(".mobile-bottom-nav", mobile_shell)
        self.assertIn(".page.active", mobile_shell)
        self.assertIn("max-width: none", mobile_shell)
        self.assertIn("padding: 88px 16px 96px", mobile_shell)
        self.assertIn("grid-template-columns: repeat(2, minmax(0, 1fr))", mobile_shell)
        self.assertIn(".tc-workspace-shell", mobile_shell)
        self.assertIn("Final mobile shell overrides", css)
        final_mobile = css.rsplit("@media (max-width: 720px)", 1)[1]
        self.assertIn(".fo-qa-day-strip", final_mobile)
        self.assertIn("overflow-x: auto", final_mobile)
        self.assertIn("#page-foundation-ops.page.active", final_mobile)
        self.assertIn("#page-foundation-ops .fo-bento-grid", final_mobile)
        self.assertIn("#page-foundation-ops .fo-bento-grid > *", final_mobile)
        self.assertIn("min-width: 0", final_mobile)
        self.assertIn(".fo-qa-grid", final_mobile)
        self.assertIn("grid-template-columns: 1fr", final_mobile)
        self.assertIn("padding: 88px 16px 96px", final_mobile)
        self.assertIn("tokenClockDegraded", script)
        self.assertIn("renderTokenClockDegradedState", script)
        self.assertIn('role="status" aria-live="polite"', script)
        self.assertIn("tc-degraded-inline", css)

    def test_ai_assets_kpis_are_data_driven(self):
        script = (ROOT / "src" / "dashboard" / "app" / "static" / "js" / "app.js").read_text(encoding="utf-8")
        css = (ROOT / "src" / "dashboard" / "app" / "static" / "css" / "style.css").read_text(encoding="utf-8")
        self.assertIn("function aaRecentActivityDate(value)", script)
        self.assertIn("function aaActiveToolCount(tools, windowDays = 30)", script)
        self.assertIn("aaActiveToolCount(tools, 30)", script)
        self.assertNotIn("Number(tool.sessionCount || 0) > 0", script)
        self.assertIn("Number(d.activeDayCount || 0).toLocaleString()", script)
        self.assertNotIn("labels.lookbackDays", script)
        self.assertIn("Number(d.agentCount ?? (d.agents||[]).length).toLocaleString()", script)
        self.assertIn("agentInstancesNote: '已检测到的本机Agent/工具实例'", script)
        self.assertIn("aa-kpi-note", script)
        self.assertIn(".aa-kpi-note", css)
        kpi_body = script.split("// A: KPIs", 1)[1].split("// B: Tools", 1)[0]
        self.assertNotIn("'67 ", kpi_body)
        self.assertNotIn('"67 ', kpi_body)

        charts_body = script.split("function renderAACharts(d)", 1)[1].split("function aaRenderInfraStatus", 1)[0]
        self.assertIn("if (typeof window.Chart !== 'function') return;", charts_body)
        self.assertLess(charts_body.index("renderHeatmap(d.trend30d || [])"), charts_body.index("typeof window.Chart"))
        self.assertLess(charts_body.index("typeof window.Chart"), charts_body.index("new Chart"))

    def test_diary_navigation_can_hide_foundation_blank_days(self):
        html = (ROOT / "src" / "dashboard" / "app" / "static" / "index.html").read_text(encoding="utf-8")
        script = (ROOT / "src" / "dashboard" / "app" / "static" / "js" / "app.js").read_text(encoding="utf-8")
        self.assertIn('id="hideInactiveDiaryDays"', html)
        self.assertIn("actanara.hideInactiveDiaryDays", script)
        self.assertIn("dates.filter(d => !d.isBlankDay)", script)
        self.assertIn("setHideInactiveDiaryDays", script)

    def test_dashboard_initialization_and_settings_rerender_are_guarded(self):
        script = (ROOT / "src" / "dashboard" / "app" / "static" / "js" / "app.js").read_text(encoding="utf-8")
        self.assertIn("ACTANARA_DIARY_NAV_READY = loadDiaryNav()", script)
        self.assertIn("await ACTANARA_DIARY_NAV_READY", script)
        self.assertIn('data-diary-date="${escapeHtml(d.fullDate)}"', script)
        self.assertIn("async function restoreDynamicDiaryPageFromHash()", script)
        self.assertIn("requestedHash.match(/^page-day-(\\d{4})$/)", script)
        self.assertIn("await showDiaryByDate(nav.dataset.diaryDate, nav)", script)
        self.assertIn("requestedHash === 'page-monthly-overview'", script)
        self.assertIn("const monthId = nav?.dataset.monthId || now.getFullYear()", script)
        self.assertIn("loadMonthlyReportById(monthId, nav)", script)
        self.assertIn("requestedHash.match(/^page-report-(\\d{4}-W\\d{2})$/)", script)
        self.assertIn("await loadReport(reportId, nav)", script)
        self.assertIn("location.hash !== '#' && await restoreDynamicDiaryPageFromHash()", script)
        self.assertIn("window.addEventListener('hashchange', () =>", script)
        self.assertIn("initFromHash().catch(e => console.error('hashchange restore error:', e))", script)
        self.assertIn("page.dataset.diaryRequestedDate = fullDate", script)
        self.assertIn("monthlyPage.dataset.monthRequestedId = mk", script)
        self.assertIn("page?.dataset.diaryRequestedDate === nav.dataset.diaryDate", script)
        self.assertIn("page?.dataset.monthRequestedId === monthId", script)
        self.assertIn("const page = requestedPage || fallbackPage", script)
        self.assertIn("window.history.replaceState(null, '', location.pathname + location.search + '#page-home')", script)
        self.assertIn("function captureSettingsFormDraft()", script)
        self.assertIn("function restoreSettingsFormDraft()", script)
        self.assertIn("rememberDashboardSettings(saved)", script)
        self.assertIn("if (window.Chart && Chart.defaults)", script)

    def test_settings_bundle_only_includes_dirty_embedded_llm_provider(self):
        script = (ROOT / "src" / "dashboard" / "app" / "static" / "js" / "app.js").read_text(encoding="utf-8")
        self.assertIn("let ACTANARA_SETTINGS_LLM_DIRTY = false;", script)
        self.assertIn('data-settings-bundle-form', script)
        dirty_body = script.split("function recordSettingsLlmDirty(event)", 1)[1].split("function isAdvancedSettingsField", 1)[0]
        self.assertIn("body?.querySelector('[data-settings-bundle-form]')", dirty_body)
        self.assertIn("input?.closest('.settings-pane[data-pane=\"llm\"]')", dirty_body)
        self.assertIn("ACTANARA_SETTINGS_LLM_DIRTY = true", dirty_body)
        self.assertIn("input.dataset.userEdited = 'true'", dirty_body)
        save_body = script.split("async function saveSettingsModal()", 1)[1].split("async function refreshRagStatus()", 1)[0]
        self.assertIn("if (ACTANARA_SETTINGS_LLM_DIRTY && document.getElementById('llmProviderName'))", save_body)
        self.assertGreaterEqual(script.count("ACTANARA_SETTINGS_LLM_DIRTY = false"), 3)
        self.assertIn("document.addEventListener('input', recordSettingsLlmDirty)", script)
        self.assertIn("document.addEventListener('change', recordSettingsLlmDirty)", script)
        toggle_body = script.split("function toggleSettingsAdvanced()", 1)[1].split("function isSettingsAdvancedVisible()", 1)[0]
        self.assertNotIn("ACTANARA_SETTINGS_LLM_DIRTY = false", toggle_body)
        standalone_body = script.split("async function openLlmProviderModal()", 1)[1].split("function renderLlmProviderModal", 1)[0]
        self.assertNotIn("ACTANARA_SETTINGS_LLM_DIRTY", standalone_body)

    def test_dashboard_shell_defines_active_label_in_both_profiles(self):
        script = (ROOT / "src" / "dashboard" / "app" / "static" / "js" / "app.js").read_text(encoding="utf-8")
        shell = script.split("const DASHBOARD_SHELL_TEXT =", 1)[1].split("const FOUNDATION_TEXT =", 1)[0]
        self.assertIn("active: '活跃'", shell)
        self.assertIn("active: 'Active'", shell)

    def test_task_board_mobile_root_actions_remain_available(self):
        html = (ROOT / "src" / "dashboard" / "app" / "static" / "tasks.html").read_text(encoding="utf-8")
        mobile = html.split("@media (max-width: 768px)", 1)[1].split("@media", 1)[0]
        self.assertIn(".root-card > .candidate-actions", mobile)
        self.assertIn("display: flex", mobile)
        self.assertIn("flex-wrap: wrap", mobile)
        self.assertIn("opacity: 1", mobile)
        self.assertNotIn(".root-card > .candidate-actions { display: none; }", mobile)

    def test_dashboard_draft_error_state_and_keyboard_contracts_are_explicit(self):
        html = (ROOT / "src" / "dashboard" / "app" / "static" / "index.html").read_text(encoding="utf-8")
        css = (ROOT / "src" / "dashboard" / "app" / "static" / "css" / "style.css").read_text(encoding="utf-8")
        script = (ROOT / "src" / "dashboard" / "app" / "static" / "js" / "app.js").read_text(encoding="utf-8")
        tasks = (ROOT / "src" / "dashboard" / "app" / "static" / "tasks.html").read_text(encoding="utf-8")

        self.assertIn("ACTANARA_SETTINGS_ADVANCED_BASELINE = new Map()", script)
        self.assertIn("function advancedSettingsFieldKey(input)", script)
        self.assertIn("'path:' + input.dataset.settingsPathGroup", script)
        self.assertIn("'runtime-source:' + input.dataset.runtimeSourceKey", script)
        self.assertIn("'external-tool:' + input.dataset.externalTool", script)
        self.assertIn("'pipeline-timeout:' + input.dataset.pipelineStepTimeout", script)
        self.assertIn("refreshAdvancedSettingsDirty()", script)
        self.assertIn("advancedDirtyCollapseBlocked", script)
        self.assertIn("const dashboard = {};", script)

        self.assertIn("function dashboardStateOf(payload)", script)
        self.assertIn("if (state.status === 'empty')", script)
        self.assertIn("if (state.status === 'degraded')", script)
        self.assertIn("if (dashboardStateFailed(d)) throw new Error(dashboardStateSummary(d))", script)
        self.assertIn("if (data.available === false)", script)
        self.assertIn("let settingsPayload = null", script)
        self.assertIn("function dashboardDialogFocusables(panel)", script)
        self.assertIn("element.getClientRects().length > 0", script)
        self.assertIn("function trapDashboardDialogFocus(event, panel)", script)
        self.assertIn("function focusDashboardRoute(page)", script)
        self.assertIn("aria-current", script)
        self.assertIn("data-settings-focus-key=\"advanced-toggle\"", script)
        self.assertIn("data-settings-focus-key=\"save\"", script)
        self.assertIn('id="settingsSaveStatus" role="status" aria-live="polite"', script)
        self.assertIn("focusSettingsControl('advanced-toggle')", script)
        self.assertIn("focusSettingsControl('save')", script)
        self.assertIn("n.removeAttribute('aria-current')", script)
        self.assertIn('data-page-id="page-day-${escapeHtml(d.date)}"', script)
        self.assertIn("if (n.dataset.pageId === hash)", script)
        self.assertNotIn("getAttribute('onclick')?.includes", script)
        self.assertIn('role="dialog" aria-modal="true"', html)
        self.assertIn("button:focus-visible", css)

        self.assertIn("function restoreTaskFocus(attribute, value)", tasks)
        self.assertIn('data-section-key="${esc(sec)}"', tasks)
        self.assertIn('data-card-key="${esc(cardKey)}"', tasks)
        self.assertIn('data-node-key="${esc(node.nodeId)}"', tasks)
        self.assertIn("taskModalReturnFocusKey", tasks)
        self.assertIn("function renderNovaTaskCandidateFailure(data)", tasks)
        self.assertIn("directWritesOpen = true", tasks)
        self.assertIn("taskSseConnected = false", tasks)
        self.assertIn("live ? t('realtimeSync') : t('snapshotLoaded')", tasks)
        self.assertIn("document.getElementById('createNodeTitle')?.focus()", tasks)
        self.assertIn(".tree-node-row:focus-within .node-actions", tasks)
        self.assertIn('role="dialog" aria-modal="true"', tasks)

    def test_dashboard_titles_are_canonical_across_runtime_and_static_demo(self):
        surfaces = {
            "runtime": ROOT / "src" / "dashboard" / "app" / "static",
            "static-demo": ROOT / "docs" / "dashboard-demo",
        }

        for name, base in surfaces.items():
            with self.subTest(surface=name):
                html = (base / "index.html").read_text(encoding="utf-8")
                script = (base / "js" / "app.js").read_text(encoding="utf-8")
                tasks = (base / "tasks.html").read_text(encoding="utf-8")
                dashboard_shell = script.split("const DASHBOARD_SHELL_TEXT =", 1)[1].split(
                    "const FOUNDATION_TEXT =", 1
                )[0]
                task_text = tasks.split("const TASK_TEXT =", 1)[1].split("function taskText", 1)[0]

                self.assertIn("<title>Actanara</title>", html)
                self.assertEqual(
                    re.findall(r"documentTitle:\s*'([^']+)'", dashboard_shell),
                    ["Actanara", "Actanara"],
                )
                self.assertIn("<title>Actanara — Nova Task</title>", tasks)
                self.assertEqual(
                    re.findall(r"documentTitle:\s*'([^']+)'", task_text),
                    ["Actanara — Nova Task", "Actanara — Nova Task"],
                )
                legacy_dashboard_brand = "Agent" + " Dashboard"
                legacy_task_title = "任务看板 — " + "Dashboard"
                self.assertNotIn(legacy_dashboard_brand, html + script + tasks)
                self.assertNotIn(legacy_task_title, tasks)

    def test_dashboard_banners_reuse_readme_asset_without_distortion(self):
        readme_banner = ROOT / "docs" / "assets" / "banner.png"
        expected_bytes = readme_banner.read_bytes()
        self.assertEqual(expected_bytes[:8], b"\x89PNG\r\n\x1a\n")
        self.assertEqual(
            (
                int.from_bytes(expected_bytes[16:20], "big"),
                int.from_bytes(expected_bytes[20:24], "big"),
            ),
            (1378, 313),
        )

        surfaces = {
            "runtime": (
                ROOT / "src" / "dashboard" / "app" / "static",
                "/static/banner.png",
            ),
            "static-demo": (ROOT / "docs" / "dashboard-demo", "banner.png"),
        }
        for name, (base, source) in surfaces.items():
            with self.subTest(surface=name):
                html = (base / "index.html").read_text(encoding="utf-8")
                css = (base / "css" / "style.css").read_text(encoding="utf-8")
                self.assertEqual((base / "banner.png").read_bytes(), expected_bytes)
                self.assertEqual(html.count(f'src="{source}"'), 2)
                self.assertEqual(html.count('width="1378" height="313"'), 2)

                sidebar = css.split(".sidebar-brand-banner {", 1)[1].split("}", 1)[0]
                welcome = css.split(".dashboard-welcome-banner {", 1)[1].split("}", 1)[0]
                self.assertIn("width: 156px", sidebar)
                self.assertIn("max-height: 44px", sidebar)
                self.assertIn("height: auto", sidebar)
                self.assertIn("object-fit: contain", sidebar)
                self.assertIn("width: min(780px, 82vw)", welcome)
                self.assertIn("height: auto", welcome)
                self.assertIn("object-fit: contain", welcome)

    def test_dashboard_sse_status_aggregates_transport_and_source_health(self):
        scripts = {
            "runtime": ROOT / "src" / "dashboard" / "app" / "static" / "js" / "app.js",
            "static-demo": ROOT / "docs" / "dashboard-demo" / "js" / "app.js",
        }

        for name, path in scripts.items():
            with self.subTest(surface=name):
                script = path.read_text(encoding="utf-8")
                status = script.split("const ACTANARA_SSE_STREAM_STATES", 1)[1].split(
                    "// ── Initialize SSE connections", 1
                )[0]
                connections = script.split("// ── Initialize SSE connections", 1)[1]

                self.assertIn("const ACTANARA_SSE_STREAM_STATES = new Map()", script)
                self.assertIn("const pending = states.filter(state => state.transport !== 'connected')", status)
                self.assertIn("if (!states.length || pending.length)", status)
                self.assertIn("state.transport === 'reconnecting'", status)
                self.assertIn("el.dataset.sourceHealth = warnings.length ? 'degraded' : 'ready'", status)
                self.assertIn("transport: 'connected', sourceWarnings: sseSourceWarnings(data)", status)
                self.assertIn("transport: 'reconnecting'", status)
                self.assertIn("connectSSE('/events/tokens',", connections)
                self.assertIn("connectSSE('/events/tasks',", connections)

    def test_ai_tool_coming_soon_card(self):
        script = (ROOT / "src" / "dashboard" / "app" / "static" / "js" / "app.js").read_text(encoding="utf-8")
        self.assertIn("更多 AI 工具支持 coming soon", script)
        self.assertIn("aa-tool-coming-soon", script)

    def test_foundation_ops_uses_scoped_bento_surface_styles(self):
        html = (ROOT / "src" / "dashboard" / "app" / "static" / "index.html").read_text(encoding="utf-8")
        css = (ROOT / "src" / "dashboard" / "app" / "static" / "css" / "style.css").read_text(encoding="utf-8")
        self.assertIn("fo-bento-grid", html)
        self.assertIn("fo-span-12", html)
        self.assertIn("fo-span-7", html)
        self.assertIn("fo-span-5", html)
        self.assertIn("Foundation Ops premium bento surface", css)
        self.assertIn("#page-foundation-ops .fo-bento-grid", css)
        self.assertIn("align-items: start", css)
        self.assertIn("grid-template-columns: repeat(12, minmax(0, 1fr))", css)
        self.assertIn("#page-foundation-ops .fo-panel", css)
        self.assertIn("backdrop-filter: blur(14px)", css)
        self.assertIn("#page-foundation-ops .fo-daily-pipeline-panel .fo-pipeline-list-row", css)
        self.assertIn("#page-foundation-ops .fo-table th", css)
        self.assertIn("white-space: normal", css)
        self.assertIn("#page-foundation-ops .fo-qa-day-card", css)
        self.assertIn("backdrop-filter: blur(12px)", css)
        self.assertIn("#page-foundation-ops .fo-qa-day-card.fo-qa-blocked", css)
        self.assertIn("#page-foundation-ops .fo-qa-day-card.fo-qa-ready", css)
        self.assertIn("#page-foundation-ops .fo-panel-title", css)
        self.assertIn("color: var(--purple)", css)

    def test_diary_pages_use_scoped_premium_reading_surfaces(self):
        script = (ROOT / "src" / "dashboard" / "app" / "static" / "js" / "app.js").read_text(encoding="utf-8")
        css = (ROOT / "src" / "dashboard" / "app" / "static" / "css" / "style.css").read_text(encoding="utf-8")
        self.assertIn("diary-page-body", script)
        self.assertIn("diary-content-stack", script)
        self.assertIn("Diary premium reading surfaces", css)
        self.assertIn("--surface-glass", css)
        self.assertIn("--surface-shadow-sm", css)
        self.assertIn('#diary-pages [id^="page-day-"].page.active', css)
        self.assertIn('#diary-pages [id^="diary-content-"].page-body', css)
        self.assertIn("#diary-pages .diary-content-stack", css)
        self.assertIn("#diary-pages .stat-card", css)
        self.assertIn("backdrop-filter: blur(12px)", css)
        self.assertIn("#diary-pages .stat-card::before", css)
        self.assertIn("display: none", css)
        self.assertIn("#diary-pages .section", css)
        self.assertIn("backdrop-filter: blur(14px)", css)
        self.assertIn("#diary-pages .section-title", css)
        self.assertIn("color: #1e2b8c", css)
        self.assertIn("diary-summary-card", script)
        self.assertIn("activityState === 'empty'", script)
        self.assertIn("const DIARY_LABELS", script)
        self.assertIn("Daily Overview", script)
        self.assertIn("No Activity Today", script)
        self.assertIn("languageProfile", script)
        self.assertIn("blank-diary-stack", script)
        self.assertIn("今日无活动", script)
        self.assertIn("diary-summary-head", script)
        self.assertIn("diary-reminder-card", script)
        self.assertIn("diary-lesson-card", script)
        self.assertIn("#diary-pages .diary-summary-card", css)
        self.assertIn("#diary-pages .blank-diary-stack", css)
        self.assertIn("#diary-pages .blank-diary-cron-row", css)
        self.assertIn("#diary-pages .diary-agent-title", css)
        self.assertIn("#diary-pages .diary-task-title", css)
        self.assertIn("font-weight: 780", css)
        self.assertIn("const hour = (idx + 4) % 24", script)
        self.assertIn("periodClass(task.period)", script)
        self.assertIn("#diary-pages .diary-period-pill.period-morning", css)
        self.assertIn("#diary-pages .diary-period-pill.period-afternoon", css)
        self.assertIn("#diary-pages .diary-period-pill.period-late-night", css)
        self.assertIn("#diary-pages .diary-period-pill.period-dawn", css)
        self.assertIn("#diary-pages .diary-reminder-card", css)
        self.assertIn("#diary-pages .diary-lesson-card summary::after", css)
        self.assertNotIn("topicPalette", script)
        self.assertIn("#diary-pages .report-body", css)
        self.assertIn("diary-note-card", script)
        self.assertIn("diary-infra-table", script)
        self.assertIn("diary-raw-title", script)
        self.assertIn("#diary-pages .diary-note-card", css)
        self.assertIn("#diary-pages .diary-infra-table", css)
        self.assertIn("#diary-pages .diary-raw-title", css)
        self.assertIn("#diary-pages .task-row:hover", css)
        final_mobile = css.rsplit("@media (max-width: 720px)", 1)[1]
        self.assertIn('#diary-pages [id^="page-day-"].page.active', final_mobile)
        self.assertIn("#diary-pages .stat-grid", final_mobile)
        self.assertIn("grid-template-columns: repeat(2, minmax(0, 1fr))", final_mobile)
        self.assertIn("#diary-pages .section", final_mobile)

    def test_diary_kpi_details_use_foundation_projection_source(self):
        script = (ROOT / "src" / "dashboard" / "app" / "static" / "js" / "app.js").read_text(encoding="utf-8")
        self.assertIn("function toggleKpiPanel(date, type)", script)
        body = script.split("function toggleKpiPanel(date, type)", 1)[1].split("function hourlyHeatmap", 1)[0]
        self.assertIn("foundationSnapshotDetail", body)
        self.assertIn("d.parsedKpi", body)
        self.assertIn("d.agentWorkNew", body)
        self.assertIn("d.sessionBySource", body)
        self.assertNotIn("d.dailyStats", body)
        self.assertNotIn("dailyStatsHeaders", body)

    def test_weekly_report_splits_summary_and_uses_compact_layout(self):
        script = (ROOT / "src" / "dashboard" / "app" / "static" / "js" / "app.js").read_text(encoding="utf-8")
        css = (ROOT / "src" / "dashboard" / "app" / "static" / "css" / "style.css").read_text(encoding="utf-8")
        self.assertIn("_summaryQuote", script)
        self.assertIn("_summaryDetailsSection", script)
        self.assertIn("wr-chart-pair", script)
        self.assertIn("shortWeek ? `${new Date().getFullYear()}-${raw}`", script)
        self.assertIn("wrSplitPeriodSummaryMarkdown", script)
        self.assertIn("wrExtractSummaryQuote", script)
        self.assertIn("wrSummaryFocusHtml", script)
        self.assertIn("wr-summary-focus-block", script)
        self.assertIn("wr-summary-detail-index", script)
        self.assertIn("wr-topic-meter", script)
        self.assertIn("wr-summary-topic-preview", script)
        self.assertIn("wr-summary-filter-pill", script)
        self.assertIn("wr-lesson-meta", script)
        self.assertIn("本周期总览", script)
        self.assertIn("关怀与鼓励", script)
        self.assertIn("由周报总结 LLM 基于本周期数据提炼", script)
        self.assertIn("data.highFrequencyTopics || data.topTopics", script)
        self.assertIn("暂无 LLM 高频主题", script)
        self.assertNotIn("+ reportFreshnessSuffix(data.dataFreshness)", script)
        self.assertLess(script.index("⏱️</span> 时间投入"), script.index("⚡</span> 周度使用趋势"))
        self.assertGreater(script.index("_summaryDetailsSection"), script.index("_lessons"))
        self.assertIn('#diary-pages [id^="page-report-"].page.active', css)
        self.assertIn('#diary-pages [id^="page-report-"] .wr-summary-quote', css)
        self.assertIn('#diary-pages [id^="page-report-"] .wr-summary-focus-block', css)
        self.assertIn('#diary-pages [id^="page-report-"] .wr-chart-pair', css)
        self.assertIn("grid-template-columns: repeat(2, minmax(0, 1fr))", css)
        self.assertIn('#diary-pages [id^="page-report-"] .wr-summary-details', css)
        self.assertIn("max-height: 520px", css)
        self.assertIn("overflow-y: auto", css)
        self.assertIn('#diary-pages [id^="page-report-"] .wr-summary-details .wr-narrative-md-section h3', css)
        self.assertIn('#diary-pages [id^="page-report-"] .wr-summary-detail-index', css)
        self.assertIn('#diary-pages [id^="page-report-"] .wr-topic-source', css)
        self.assertIn('#diary-pages [id^="page-report-"] .wr-topic-list', css)
        self.assertIn('#diary-pages [id^="page-report-"] .wr-topic-meter', css)
        self.assertIn('#diary-pages [id^="page-report-"] .wr-summary-topic-item', css)
        self.assertIn('#diary-pages [id^="page-report-"] .wr-summary-topic-preview', css)
        self.assertIn('#diary-pages [id^="page-report-"] .wr-lesson-card', css)
        self.assertIn(".wr-summary-filter-pill.active", css)
        self.assertIn('#diary-pages [id^="page-report-"] .wr-summary-topic-title small', css)
        self.assertIn('#diary-pages [id^="page-report-"] .wr-lesson-meta', css)
        final_mobile = css.rsplit("@media (max-width: 720px)", 1)[1]
        self.assertIn('#diary-pages [id^="page-report-"] .wr-chart-pair', final_mobile)
        self.assertIn("grid-template-columns: 1fr", final_mobile)

    def test_monthly_navigation_tracks_selected_month_and_stale_responses(self):
        script = (ROOT / "src" / "dashboard" / "app" / "static" / "js" / "app.js").read_text(encoding="utf-8")
        self.assertIn("let MR_CURRENT_MONTH = null;", script)
        self.assertIn("let MR_REQUEST_TOKEN = 0;", script)
        self.assertIn("MR_LOADED[mk] && MR_CURRENT_MONTH === mk", script)
        self.assertIn("const requestToken = ++MR_REQUEST_TOKEN;", script)
        self.assertRegex(script, re.compile(r"requestToken !== MR_REQUEST_TOKEN \\|\\| MR_CURRENT_MONTH !== mk"))

    def test_summary_buttons_use_exact_current_period(self):
        script = (ROOT / "src" / "dashboard" / "app" / "static" / "js" / "app.js").read_text(encoding="utf-8")
        html = (ROOT / "src" / "dashboard" / "app" / "static" / "index.html").read_text(encoding="utf-8")
        self.assertIn("refreshWeeklySummary(reportId, prefix)", script)
        self.assertIn("refreshPeriodSummary(startDate, 7", script)
        self.assertIn("refreshMonthlySummary()", script)
        self.assertIn("refreshPeriodSummary(mk + '-01', days", script)
        self.assertIn('id="mrRefreshSummaryBtn"', html)

    def test_dashboard_shell_i18n_is_profile_aware_and_keeps_zh_defaults(self):
        script = (ROOT / "src" / "dashboard" / "app" / "static" / "js" / "app.js").read_text(encoding="utf-8")
        html = (ROOT / "src" / "dashboard" / "app" / "static" / "index.html").read_text(encoding="utf-8")
        self.assertIn("const DASHBOARD_SHELL_TEXT", script)
        self.assertIn("function applyStaticDashboardText(profile)", script)
        self.assertIn("const labels = { ...dashboardText(profile), ...dashboardShellText(profile), ...aiAssetsText(profile) }", script)
        self.assertIn("function updateMonthlyReportLabels()", script)
        self.assertIn("document.documentElement.lang = dashboardLanguageProfile(profile) === 'en' ? 'en-US' : 'zh-CN'", script)
        self.assertIn("applyStaticDashboardText(ACTANARA_PIPELINE_LANGUAGE_PROFILE)", script)
        self.assertIn("ensureDashboardLanguageProfile().then(profile => applyStaticDashboardText(profile))", script)
        self.assertIn("AI Assets Overview", script)
        self.assertIn("Foundation Ops", script)
        self.assertIn("Generate Historical Data", script)
        self.assertIn('data-i18n="navTodayOverview"', html)
        self.assertIn('data-i18n="foundationOpsTitle"', html)
        self.assertIn('data-i18n-placeholder="ragSearchPlaceholder"', html)
        self.assertIn('data-i18n="aiAssetsWorkspaceRanking"', html)
        self.assertIn('data-i18n="runtimeRegistry"', html)
        self.assertIn('data-i18n-aria-label="back"', html)
        self.assertIn('id="aaDocModalTitle" data-i18n="documentFallback"', html)
        self.assertIn('id="foCompleteness" data-i18n="loadingEllipsis"', html)
        self.assertIn('id="foCadence" data-i18n="loadingEllipsis"', html)
        self.assertIn('id="foRuntime" data-i18n="loadingEllipsis"', html)
        self.assertIn('data-i18n="monthlyOverviewTitle"', html)
        self.assertIn('data-i18n="monthlyUsageTrend"', html)
        self.assertIn('id="mr_summaryQuote"', html)
        self.assertIn('id="mr_summaryDetailsSection"', html)
        self.assertIn('id="mr_summaryDetails"', html)
        self.assertIn('data-i18n-title="generateMonthlySummaryTitle"', html)
        self.assertIn('data-i18n="diaryNavLoading"', html)
        self.assertIn('data-i18n="detailedDiary"', html)
        self.assertIn('data-i18n="saveChanges"', html)
        self.assertIn("Agent / Workspace Usage Ranking", script)
        self.assertIn("Runtime Registry", script)
        self.assertIn("monthlyOverviewTitle: 'Monthly Reports'", script)
        self.assertIn("diaryNavWeeklyOverview: 'Weekly Overview'", script)
        self.assertIn("labels.diaryNavMonthlyOverview", script)
        self.assertIn("saveChanges: 'Save Changes'", script)
        self.assertIn("noWorkspaceUsageToday: 'No Agent / Workspace usage data today'", script)
        self.assertIn("todayDetails: 'Today · click for details'", script)
        self.assertIn("const labels = dashboardShellText();", script)
        self.assertIn("modalBack: '← Back'", script)
        self.assertIn("allTimeTokens: 'All-Time Tokens'", script)
        self.assertIn("documentFallback: 'Document'", script)
        self.assertIn("profileLabel: 'Profile'", script)
        self.assertIn("labels.documentFallback", script)
        self.assertIn("assetLabels.tokenUnit", script)
        self.assertIn('当日实时总览', html)
        self.assertIn('Foundation 运维', html)
        self.assertIn('搜索 Actanara 长期记忆', html)

    def test_ai_assets_infrastructure_panel_limits_devices_and_services(self):
        script = (ROOT / "src" / "dashboard" / "app" / "static" / "js" / "app.js").read_text(encoding="utf-8")
        css = (ROOT / "src" / "dashboard" / "app" / "static" / "css" / "style.css").read_text(encoding="utf-8")
        html = (ROOT / "src" / "dashboard" / "app" / "static" / "index.html").read_text(encoding="utf-8")
        self.assertIn("const AA_INFRA_CARD_LIMIT = 6", script)
        self.assertIn("function toggleAaInfrastructure(kind)", script)
        self.assertIn("function openAaInfraActivityModal(activityIndex)", script)
        self.assertIn("window.openAaInfraActivityModal = openAaInfraActivityModal;", script)
        self.assertIn("function renderAaInfrastructure(d, labels)", script)
        self.assertIn("if (_aaState.data) renderAaInfrastructure(_aaState.data, aiAssetsText());", script)
        self.assertIn("基础设施（beta）", html)
        self.assertIn("Infrastructure (Beta)", script)
        self.assertIn('class="aa-infra-shell" id="aaDevices"', html)
        self.assertIn("renderInfraSection('devices'", script)
        self.assertIn("renderInfraSection('services'", script)
        self.assertIn("labels.deviceKindTag", script)
        self.assertIn("labels.serviceKindTag", script)
        self.assertIn("if (part === undefined || part === null) return false;", script)
        self.assertIn("aa-infra-card-actions", script)
        self.assertIn('<summary class="aa-infra-card-top">', script)
        self.assertIn("aa-infra-card-detail", script)
        self.assertIn("openModal(labels.recentActivity", script)
        self.assertNotIn("aa-device-emoji", script)
        self.assertNotIn("aa-device-summary", script)
        self.assertIn("items.slice(0, AA_INFRA_CARD_LIMIT)", script)
        self.assertIn("grid-template-columns: repeat(3, minmax(0, 1fr));", css)
        self.assertIn(".aa-devices-grid { grid-template-columns: repeat(2, minmax(0, 1fr)); }", css)
        self.assertIn(".aa-infra-shell", css)
        self.assertIn(".aa-infra-toggle", css)
        self.assertIn(".aa-infra-header", css)
        self.assertIn(".aa-infra-kind-tag", css)
        self.assertIn(".aa-infra-meta-line", css)
        self.assertIn(".aa-infra-activity-button", css)
        self.assertIn(".aa-infra-activity-list", css)
        self.assertIn(".aa-infra-card-top::after", css)
        self.assertIn("font-size: 26px;", css)
        self.assertIn("position: absolute;", css)
        self.assertIn("padding: 16px 42px 16px 18px;", css)
        self.assertIn(".aa-infra-card[open] .aa-infra-card-top::after", css)

    def test_ai_assets_storage_splits_actanara_and_tool_cards(self):
        script = (ROOT / "src" / "dashboard" / "app" / "static" / "js" / "app.js").read_text(encoding="utf-8")
        css = (ROOT / "src" / "dashboard" / "app" / "static" / "css" / "style.css").read_text(encoding="utf-8")
        html = (ROOT / "src" / "dashboard" / "app" / "static" / "index.html").read_text(encoding="utf-8")
        service = (ROOT / "src" / "dashboard" / "app" / "services" / "ai_assets.py").read_text(encoding="utf-8")

        self.assertIn('class="aa-storage-cards" id="aaStorage"', html)
        self.assertIn("function aaFormatStorageMB(value)", script)
        self.assertIn("escapeHtml(labels.artifactDetails)", script)
        self.assertIn("escapeHtml(labels.toolStorage)", script)
        self.assertLess(script.index("escapeHtml(labels.artifactDetails)"), script.index("escapeHtml(labels.toolStorage)"))
        self.assertIn("chart-card aa-storage-card", script)
        self.assertIn(".aa-storage-cards", css)
        self.assertIn("grid-template-columns: repeat(2, minmax(0, 1fr));", css)
        self.assertIn('storageRagIndex": "RAG 索引"', service)
        self.assertIn('paths.archives_dir', service)
        self.assertIn('resolve_rag_settings().v2_store_path / "indexes"', service)

    def test_foundation_ops_dynamic_copy_uses_profile_text_tables(self):
        script = (ROOT / "src" / "dashboard" / "app" / "static" / "js" / "app.js").read_text(encoding="utf-8")

        self.assertIn("manualOnly: '执行状态：manual-only'", script)
        self.assertIn("manualOnly: 'Execution state: manual-only'", script)
        self.assertIn("readingDailyQa: '读取 Daily QA…'", script)
        self.assertIn("readingDailyQa: 'Reading Daily QA...'", script)
        self.assertIn("noCompletenessData: '无 completeness 数据'", script)
        self.assertIn("noCompletenessData: 'No completeness data'", script)
        self.assertIn("periodLabel = periodLabel || labels.monthlyKnowledgePeriod", script)
        self.assertIn("return labels.statusLabels[status] || status || labels.statusLabels.unknown", script)
        self.assertNotIn("dashboardLanguageProfile() === 'en' ? 'Monthly' : '本月'", script)
        self.assertNotIn("dashboardLanguageProfile() === 'en' ? 'Reading Daily QA...'", script)
        self.assertNotIn("dashboardLanguageProfile() === 'en' ? 'Execution state: manual-only'", script)

    def test_missing_snapshot_notice_can_trigger_period_refresh(self):
        script = (ROOT / "src" / "dashboard" / "app" / "static" / "js" / "app.js").read_text(encoding="utf-8")
        html = (ROOT / "src" / "dashboard" / "app" / "static" / "index.html").read_text(encoding="utf-8")
        self.assertIn("function reportNeedsAssetRefresh(meta)", script)
        self.assertIn("function wrRenderRefreshNotice(prefix, freshness, startDate, days, reload)", script)
        self.assertIn("重新聚合数据", script)
        self.assertIn("refreshPeriodAssets(startDate, days, buttonId, reload)", script)
        self.assertIn('id="mr_refreshNotice"', html)

    def test_single_diary_missing_snapshot_can_trigger_day_refresh(self):
        script = (ROOT / "src" / "dashboard" / "app" / "static" / "js" / "app.js").read_text(encoding="utf-8")
        self.assertIn("function diaryNeedsRefresh(freshness)", script)
        self.assertIn("freshness.diaryPage.source === 'snapshot-missing'", script)
        self.assertIn("function renderDiaryRefreshNotice(contentEl, fullDate, shortDate, navEl)", script)
        self.assertIn("正在读取日记快照", script)
        self.assertIn("refreshPeriodAssets(fullDate, 1, buttonId", script)

    def test_foundation_ops_panel_exposes_refresh_jobs_and_manual_backfill(self):
        script = (ROOT / "src" / "dashboard" / "app" / "static" / "js" / "app.js").read_text(encoding="utf-8")
        css = (ROOT / "src" / "dashboard" / "app" / "static" / "css" / "style.css").read_text(encoding="utf-8")
        html = (ROOT / "src" / "dashboard" / "app" / "static" / "index.html").read_text(encoding="utf-8")
        self.assertIn('id="page-foundation-ops"', html)
        self.assertIn("Foundation 运维", html)
        self.assertIn("function loadFoundationOps()", script)
        self.assertIn('id="foDailyQa"', html)
        self.assertIn('id="foDailyQaOverview"', html)
        self.assertIn('id="foDailyQaDate"', html)
        self.assertIn('id="foDailyPipelineSummary"', html)
        self.assertIn('id="foDailyPipelineDate"', html)
        self.assertIn('id="foRepairRuns"', html)
        self.assertIn("function loadFoundationDailyQa()", script)
        self.assertIn("function loadFoundationDailyQaOverview()", script)
        self.assertIn("function loadFoundationDailyPipelineSummary()", script)
        self.assertIn("function foRenderDailyPipelineSummary(payload)", script)
        self.assertIn("ready: '就绪'", script)
        self.assertIn("Blank-day fast path 已跳过 Nova-Task evidence", script)
        self.assertIn("function loadFoundationRepairRuns()", script)
        self.assertIn("function foRenderRepairRuns(payload)", script)
        self.assertIn("function runDurationSeconds(run)", script)
        self.assertIn("function foRenderDailyQaOverview(payload)", script)
        self.assertIn("function foRenderDailyQa(payload)", script)
        self.assertIn("function foRenderDailyQaRepairCommands(commands)", script)
        self.assertIn("function foRenderDailyQaRepairPolicy(policy)", script)
        self.assertIn("function foRenderDailyQaRepairRunControl(item, index)", script)
        self.assertIn("function copyFoundationRepairCommand(index)", script)
        self.assertIn("function runFoundationRepairCommand(index)", script)
        self.assertIn("function waitForFoundationRepairRun(runId, updateStatus)", script)
        self.assertIn("window.FOUNDATION_REPAIR_COMMANDS", script)
        self.assertIn("navigator.clipboard.writeText", script)
        self.assertIn("policy.dashboardExecutable", script)
        self.assertIn("confirmationText", script)
        self.assertIn("fetch('/api/foundation/ops/daily-qa/repair-runs'", script)
        self.assertIn("fetch('/api/foundation/ops/daily-qa/repair-runs/' + runId)", script)
        self.assertIn("fetch('/api/foundation/ops/daily-qa/repair-runs?limit=20')", script)
        self.assertIn("fo-copy-status-", script)
        self.assertIn("fo-repair-run-status-", script)
        self.assertIn("修复执行审计", html)
        self.assertIn('aria-live="polite"', script)
        self.assertIn("payload.repairCommands", script)
        self.assertIn("修复命令", script)
        self.assertIn("item.summary", script)
        self.assertIn("item.action", script)
        self.assertIn("影响：", script)
        self.assertIn("fetch('/api/foundation/ops/daily-qa?date='", script)
        self.assertIn("fetch('/api/foundation/ops/daily-qa/overview?end='", script)
        self.assertIn("fetch('/api/foundation/ops/daily-pipeline-summary?date='", script)
        self.assertIn("fo-pipeline-stats", script)
        self.assertIn("fo-pipeline-list-row", script)
        self.assertIn("Blank-day fast path", script)
        self.assertIn("latestBlankInputsRun", script)
        self.assertIn(".fo-blank-day-note", css)
        self.assertIn('id="foCompleteness"', html)
        self.assertIn('id="foCadence"', html)
        self.assertIn("function foRenderCompleteness(matrix)", script)
        self.assertIn("function foRenderCadence(cadence)", script)
        self.assertIn("fetch('/api/foundation/ops/snapshot?limit=30')", script)
        self.assertIn("data.projectionCompleteness", script)
        self.assertIn("data.scheduledRunCadence", script)
        self.assertIn("data.refreshJobs", script)
        self.assertIn("function foundationRefreshToday()", script)
        self.assertIn("function foundationRefreshCurrentWeek()", script)
        self.assertIn("function foundationRefreshCurrentMonth()", script)
        self.assertIn("function foundationBackfillRange()", script)
        self.assertIn("fetch('/api/foundation/backfill'", script)
        self.assertIn('id="foBackfillStart"', html)
        self.assertIn('id="foBackfillEnd"', html)
        self.assertIn("loadFoundationOps();", script)

    def test_task_board_exposes_nova_task_candidate_review_and_v2_patch_bridge(self):
        html = (ROOT / "src" / "dashboard" / "app" / "static" / "tasks.html").read_text(encoding="utf-8")
        app_script = (ROOT / "src" / "dashboard" / "app" / "static" / "js" / "app.js").read_text(encoding="utf-8")
        router = (ROOT / "src" / "dashboard" / "app" / "routers" / "tasks.py").read_text(encoding="utf-8")
        review_service = (ROOT / "src" / "dashboard" / "app" / "services" / "nova_task_review.py").read_text(encoding="utf-8")
        ai_assets_router = (ROOT / "src" / "dashboard" / "app" / "routers" / "ai_assets.py").read_text(encoding="utf-8")
        diary_service = (ROOT / "src" / "dashboard" / "app" / "services" / "diary.py").read_text(encoding="utf-8")
        self.assertIn('id="novaTaskCandidatePanel"', html)
        self.assertIn('id="novaTaskCandidateList"', html)
        self.assertIn("const TASK_TEXT", html)
        self.assertIn("async function ensureTaskLanguageProfile()", html)
        self.assertIn("await ensureTaskLanguageProfile();", html)
        self.assertIn("document.documentElement.lang = taskLanguageProfile === 'en' ? 'en-US' : 'zh-CN'", html)
        self.assertIn('data-i18n="pageTitle"', html)
        self.assertIn('data-i18n-placeholder="searchPlaceholder"', html)
        self.assertIn("pageTitle: 'Task Board'", html)
        self.assertIn("suggestParentTask: 'Suggest adding a top-level node'", html)
        self.assertIn("t('lastUpdated'", html)
        self.assertIn("t('pendingReviewCount'", html)
        self.assertIn("function renderCandidateMetadata(item)", html)
        self.assertIn("function anchorProfileLabel(profile)", html)
        self.assertIn("plannedPathlessL1", html)
        self.assertIn("observedPathBackedL1", html)
        self.assertIn("fetch('/api/tasks/l1-review/status')", html)
        self.assertIn("fetch('/api/tasks/l1-review?status=pending_review&limit=20')", html)
        self.assertIn('id="planningImportFile"', html)
        self.assertIn("function importPlanningFile(file)", html)
        self.assertIn("function openPlanningImportPreview(data)", html)
        self.assertIn("function applyPlanningImportArtifact(artifactPath)", html)
        self.assertIn("function planningActionTags(node)", html)
        self.assertIn("function childNodeTypeForParent(parentNodeId)", html)
        self.assertIn("nodeType: childNodeTypeForParent(parentNodeId)", html)
        self.assertNotIn("nodeType: 'subtask', parentNodeId", html)
        self.assertIn("validationReport.summary", html)
        self.assertIn("fetch('/api/tasks/planning-import'", html)
        self.assertIn("fetch('/api/tasks/planning-import/apply'", html)
        self.assertIn('@router.get("/tasks/direct-writes/recent")', router)
        self.assertIn("/api/tasks/l1-review/${candidateId}/${action}", html)
        self.assertNotIn("function showCandidateMergeSelector(candidateId)", html)
        self.assertNotIn("function mergeNovaTaskCandidateIntoNode(candidateId)", html)
        self.assertNotIn("function showCandidateSupersedeSelector(candidateId)", html)
        self.assertNotIn("function supersedeNovaTaskCandidateWithCandidate(candidateId)", html)
        self.assertIn('@router.get("/tasks/l1-review/status")', router)
        self.assertIn('@router.get("/tasks/l1-review")', router)
        self.assertIn('@router.post("/tasks/candidates/{candidate_id}/merge")', router)
        self.assertIn('@router.post("/tasks/candidates/{candidate_id}/supersede")', router)
        self.assertIn("fetch('/api/tasks', { keepalive: true })", html)
        self.assertIn("/api/tasks/nodes/${encodeURIComponent(nodeId)}", html)
        self.assertIn("findUniqueAuthorityNodeByTitle", html)
        self.assertNotIn("body: JSON.stringify({content, done: newDone})", html)
        self.assertIn("function novaTaskTreeToDashboardTasks(data)", app_script)
        self.assertIn("dashboardTasksFromPayload(data)", app_script)
        self.assertNotIn("window._taskBoardData = data.tasks", app_script)
        self.assertNotIn("const tasks = data.tasks || []", app_script)
        self.assertNotIn("nova_task_review.update_node_by_legacy_content", router)
        self.assertNotIn("update_node_by_legacy_content", review_service)
        self.assertNotIn('@router.patch("/tasks")', router)
        self.assertNotIn("tasks.toggle_task(content, done)", router)
        self.assertNotIn("read_raw()", router)
        self.assertNotIn("parse_board(", router)
        self.assertIn("nova_task_review.task_board_payload", router)
        self.assertIn('"authority": "nova-task-v2-sqlite"', review_service)
        self.assertIn("nova_task_review.task_board_payload", ai_assets_router)
        self.assertIn("foundation.nova_task_enabled()", ai_assets_router)
        self.assertNotIn("read_raw()", ai_assets_router)
        self.assertNotIn("parse_board(", ai_assets_router)
        self.assertNotIn("legacy-task-board", ai_assets_router)
        self.assertNotIn("read_raw()", diary_service)
        self.assertNotIn("parse_board(", diary_service)

    def test_report_list_and_detail_are_foundation_document_consumers(self):
        router = (ROOT / "src" / "dashboard" / "app" / "routers" / "diary.py").read_text(encoding="utf-8")
        self.assertIn("read_diary_markdown_documents", router)
        self.assertIn("foundation-diary-markdown-documents", router)
        self.assertNotIn("iter_diary_markdown_files", router)
        self.assertNotIn("diary_learning_report_path", router)
        self.assertNotIn("fpath.read_text", router)

    def test_bottom_settings_buttons_and_modals_are_wired(self):
        script = (ROOT / "src" / "dashboard" / "app" / "static" / "js" / "app.js").read_text(encoding="utf-8")
        html = (ROOT / "src" / "dashboard" / "app" / "static" / "index.html").read_text(encoding="utf-8")
        css = (ROOT / "src" / "dashboard" / "app" / "static" / "css" / "style.css").read_text(encoding="utf-8")
        router = (ROOT / "src" / "dashboard" / "app" / "routers" / "settings.py").read_text(encoding="utf-8")
        ai_assets_service = (ROOT / "src" / "dashboard" / "app" / "services" / "ai_assets.py").read_text(encoding="utf-8")
        self.assertIn("sidebar-bottom-nav", html)
        self.assertIn("sidebar-utility", html)
        self.assertLess(html.index("sidebar-bottom-nav"), html.index("sidebar-utility"))
        self.assertIn("openSettingsModal()", html)
        self.assertIn("openLlmProviderModal()", html)
        self.assertIn("openGithubTodo()", html)
        self.assertIn("openI18nTodo()", html)
        self.assertIn("function openSettingsModal()", script)
        self.assertIn("fetch('/api/settings')", script)
        self.assertIn("function saveSettingsModal()", script)
        save_settings_body = script.split("async function saveSettingsModal()", 1)[1].split("async function refreshRagStatus()", 1)[0]
        self.assertIn("fetch('/api/settings/bundle'", save_settings_body)
        self.assertNotIn("bundle.rag = collectRagSettingsFromModal()", save_settings_body)
        self.assertIn("bundle.llmProvider = collectLlmProviderSettingsFromModal()", save_settings_body)
        self.assertIn("collectLlmProviderSettingsFromModal()", save_settings_body)
        self.assertIn("general: collectGeneralSettingsFromModal()", save_settings_body)
        self.assertIn("schedule: collectScheduleSettingsFromModal()", save_settings_body)
        self.assertIn("const advancedVisible = isSettingsAdvancedVisible()", save_settings_body)
        self.assertIn("if (advancedVisible)", save_settings_body)
        self.assertIn("dashboard: collectDashboardSettingsFromModal()", save_settings_body)
        self.assertIn("payload.paths = collectPathSettingsFromModal()", save_settings_body)
        self.assertIn("payload.runtimeSources = collectRuntimeSourceSettingsFromModal()", save_settings_body)
        self.assertIn("payload.pipeline = collectPipelineSettingsFromModal()", save_settings_body)
        self.assertIn("payload.externalTools = collectExternalToolSettingsFromModal()", save_settings_body)
        self.assertIn("DASHBOARD_RESTART_COMMAND", script)
        self.assertIn("actanara dashboard restart", script)
        self.assertIn('id="page-home" class="page active"', html)
        self.assertIn('id="page-overview" class="page"', html)
        self.assertIn("sidebar-brand-banner", html)
        self.assertNotIn(">ACTANARA</", html)
        self.assertEqual(html.count('src="/static/banner.png"'), 2)
        self.assertIn("ragExternalSources", script)
        self.assertIn("previewRagExternalSources", script)
        self.assertIn("/api/rag/external-sources/plan", script)
        self.assertIn(".doc is unsupported", script)
        self.assertIn("sidebar-brand-home", html)
        self.assertIn("dashboard-welcome", html)
        home_block = html.split('id="page-home"', 1)[1].split('id="page-overview"', 1)[0]
        overview_block = html.split('id="page-overview"', 1)[1].split('id="page-static"', 1)[0]
        self.assertIn("dashboard-welcome", home_block)
        self.assertNotIn("dashboard-welcome", overview_block)
        self.assertIn("welcomeTagline", script)
        self.assertIn("|| 'page-home'", script)
        self.assertIn("ragStartServerBtn", html)
        self.assertIn("function ragSearchStartServer()", script)
        self.assertIn("rag-status-grid", script)
        self.assertIn("rag-status-card", script)
        self.assertIn("String((idx + 4) % 24).padStart(2, '0')", script)
        self.assertIn("function copyDashboardRestartCommand()", script)
        self.assertIn("function toggleSettingsAdvanced()", script)
        self.assertIn("Advanced ${showAdvanced ? 'On' : 'Off'}", script)
        self.assertIn("dashboardRestartCopyStatus", script)
        self.assertIn("启动参数变更需重启 Dashboard", save_settings_body)
        pipeline_settings_body = script.split("function collectPipelineSettingsFromModal()", 1)[1].split("function collectLlmProviderSettingsFromModal()", 1)[0]
        self.assertNotIn("languageProfile", pipeline_settings_body)
        self.assertNotIn("englishEnabled", pipeline_settings_body)
        self.assertNotIn("fetch('/api/rag/settings'", save_settings_body)
        self.assertNotIn("fetch('/api/llm-provider'", save_settings_body)
        self.assertIn("data-tab=\"general\"", script)
        self.assertIn("data-pane=\"general\"", script)
        self.assertIn("data-tab=\"network\"", script)
        self.assertIn("data-pane=\"network\"", script)
        self.assertIn("renderNetworkSettings(dashboard)", script)
        self.assertIn("function renderNetworkSettings(dashboard)", script)
        self.assertIn("Dashboard 网络访问", script)
        self.assertIn("Tailscale", script)
        self.assertIn("id=\"setDashboardHost\"", script)
        self.assertIn("id=\"setDashboardPort\"", script)
        self.assertIn("id=\"setDashboardPublicBaseUrl\"", script)
        self.assertIn("id=\"setDashboardAllowedOrigins\"", script)
        self.assertIn("dashboard.allowedOrigins = String(originsInput.value || '')", script)
        self.assertIn(".split(/\\r?\\n|,/)", script)
        self.assertIn("data-tab=\"runtimeSources\"", script)
        self.assertIn("data-pane=\"runtimeSources\"", script)
        self.assertIn("<option value=\"foundation\" selected>foundation</option>", script)
        self.assertNotIn("['foundation','legacy'].map", script)
        runtime_source_body = script.split("function renderRuntimeSourceSettings(runtimeSources)", 1)[1].split("function renderWorkspaceAttributionSettings()", 1)[0]
        self.assertNotIn("llmGeneration", runtime_source_body)
        self.assertIn("data-tab=\"pipeline\"", script)
        self.assertIn("data-pane=\"pipeline\"", script)
        self.assertIn("data-tab=\"externalTools\"", script)
        self.assertIn("data-pane=\"externalTools\"", script)
        self.assertIn("data-tab=\"startup\"", script)
        self.assertIn("data-pane=\"startup\"", script)
        self.assertIn("function renderStartupSettings()", script)
        self.assertIn("function loadStartupServices(", script)
        self.assertIn("function toggleStartupService(kind, checked)", script)
        self.assertIn("function applyStartupServiceAction(kind, action)", script)
        self.assertIn("ACTANARA_STARTUP_PREVIEWS", script)
        self.assertIn("startupDashboardServer: 'Dashboard server'", script)
        self.assertIn("startupRagServer: 'nova-RAG / Embedding server'", script)
        self.assertNotIn("settings.authority || {}).settingsAuthority", script)
        self.assertIn("data-tab=\"llm\"", script)
        self.assertIn("data-pane=\"llm\"", script)
        self.assertIn("renderLlmProviderSettings(llmProvider, false, showAdvanced)", script)
        self.assertNotIn("data-tab=\"onboarding\"", script)
        self.assertNotIn("data-pane=\"onboarding\"", script)
        self.assertIn("function loadOnboardingReadiness()", script)
        self.assertIn("function selectedOnboardingProfiles()", script)
        self.assertIn("fetch('/api/onboarding/status' + query)", script)
        self.assertIn("fetch('/api/onboarding/plan' + query)", script)
        self.assertIn("data-onboarding-profile", script)
        self.assertIn("data-tab=\"authority\"", script)
        self.assertIn("data-pane=\"authority\"", script)
        self.assertIn("renderSettingsAuthority((authority || {}).settingsAuthority || {})", script)
        self.assertNotIn("data-tab=\"features\"", script)
        self.assertNotIn("data-pane=\"features\"", script)
        self.assertNotIn("data-feature-key", script)
        self.assertNotIn("renderFeatureSettings", script)
        self.assertNotIn("data-tab=\"future\"", script)
        self.assertNotIn("data-pane=\"future\"", script)
        self.assertIn("renderPathSettings(paths, settings.runtimePath || {})", script)
        self.assertIn("['runtime', 'database'", script)
        self.assertNotIn("data-settings-path-key=\"actanaraHome\"", script)
        self.assertIn("id=\"runtimePathCandidate\"", script)
        self.assertIn("data-requires-restart=\"dashboard\"", script)
        self.assertIn("id=\"setDashboardProjectRoot\"", script)
        self.assertIn("id=\"setDashboardServiceLabel\"", script)
        self.assertNotIn("data-settings-path-key=\"legacyDiaryRoot\"", script)
        self.assertNotIn("runtimePathAction('import_legacy')", script)
        self.assertNotIn("importLegacyDiary", script)
        self.assertNotIn("legacy-fallback", script)
        self.assertIn("检查 Diary / SQLite 一致性", script)
        self.assertIn("fetch('/api/settings/diary-path/consistency')", script)
        self.assertIn('@router.post("/settings/diary-path/rebuild")', router)
        self.assertIn("id=\"diaryRebuildStartDate\"", script)
        self.assertIn("id=\"diaryRebuildEndDate\"", script)
        self.assertIn("Diary projection 与 token usage 修复", script)
        self.assertIn("includeUsage: true", script)
        self.assertIn("token usage events", script)
        self.assertIn("diaryProjectionRebuild(true)", script)
        self.assertIn("diaryProjectionRebuild(false)", script)
        self.assertIn("REBUILD ACTANARA DIARY PROJECTIONS", script)
        self.assertIn("payload.confirmationText = confirmationText", script)
        self.assertIn("fetch('/api/settings/diary-path/rebuild'", script)
        self.assertIn("fetch('/api/settings/diary-path/rebuild/jobs?limit=10')", script)
        self.assertIn("setDiaryRebuildRangeFromConsistency(data)", script)
        self.assertIn("data.mismatchDateRange || data.diskDateRange || data.databaseDateRange", script)
        self.assertIn('@router.post("/settings/sqlite-cache/rebuild")', router)
        self.assertIn("sqliteCacheRebuild(true)", script)
        self.assertIn("sqliteCacheRebuild(false)", script)
        self.assertIn("REBUILD ACTANARA SQLITE CACHE", script)
        self.assertIn("fetch('/api/settings/sqlite-cache/rebuild'", script)
        self.assertIn("settings-progress-bar", css)
        self.assertIn('@router.get("/settings/diary-path/rebuild/jobs")', router)
        self.assertIn("function loadSystemTimerPreview()", script)
        self.assertIn("function syncSystemSchedulerCheckboxWithActual()", script)
        self.assertIn("fetch('/api/settings/scheduler')", script)
        self.assertIn("actualRegistered", script)
        self.assertIn("fetch('/api/settings/scheduler/system-timer/preview')", script)
        self.assertIn("fetch('/api/settings/scheduler/system-timer/install'", script)
        self.assertIn("fetch('/api/settings/scheduler/system-timer/uninstall'", script)
        self.assertIn("外部 Agent 仅负责按提示词触发任务", script)
        self.assertIn("Disable or uninstall the system scheduler first", script)
        self.assertIn('id="agentSchedulePromptText"', script)
        self.assertIn("function copyAgentSchedulePrompt()", script)
        self.assertIn("navigator.clipboard.writeText(prompt)", script)
        self.assertIn("agentSchedulePromptCopyStatus", script)
        self.assertIn("promptCopied: '提示词已复制'", script)
        self.assertIn("promptCopied: 'Prompt copied'", script)
        self.assertIn('@router.get("/settings/launcher/dashboard/preview")', router)
        self.assertIn('@router.post("/settings/launcher/dashboard/install")', router)
        self.assertIn('@router.post("/settings/launcher/dashboard/uninstall")', router)
        self.assertIn('@router.get("/settings/launcher/rag/preview")', router)
        self.assertIn('@router.post("/settings/launcher/rag/install")', router)
        self.assertIn('@router.post("/settings/launcher/rag/uninstall")', router)
        self.assertIn('@router.get("/settings/services/{kind}/preview")', router)
        self.assertIn('@router.post("/settings/services/{kind}/{action}")', router)
        self.assertIn("fetch('/api/settings/services/dashboard/preview')", script)
        self.assertIn("fetch('/api/settings/services/rag/preview')", script)
        self.assertIn("'/api/settings/services/' + encodeURIComponent(kind)", script)
        self.assertNotIn("fetch('/api/settings/launcher/", script)
        self.assertNotIn("LAUNCHAGENT'", script)
        self.assertIn("actualRegistered", script)
        self.assertIn("registrationMismatch", script)
        self.assertIn("function openPathBrowser(group, key", script)
        self.assertIn("fetch('/api/settings/path-browser?path='", script)
        self.assertIn("class=\"settings-browse-btn\"", script)
        self.assertIn("function runtimePathAction(mode)", script)
        self.assertIn("fetch('/api/settings/runtime-path/validate?path='", script)
        self.assertIn("fetch('/api/settings/runtime-path/select'", script)
        self.assertIn("SELECT ACTANARA RUNTIME PATH", script)
        self.assertIn("runtimePathConfirmationPrompt", script)
        self.assertIn("JSON.stringify({path, mode, confirmationText})", script)
        self.assertIn("renderRuntimePathStatus(data, mode)", script)
        self.assertIn("function openLlmProviderModal()", script)
        self.assertIn("fetch('/api/llm-provider-chain')", script)
        self.assertIn("function renderLlmProviderSettings(provider, includeActions, showAdvanced = true)", script)
        self.assertIn("<select id=\"llmProviderName\"", script)
        self.assertIn("llmProviderCatalogChanged()", script)
        self.assertIn("llmProviderModelSelect", script)
        self.assertIn("llmProviderContextWindow", script)
        self.assertIn("llmProviderTimeoutSeconds", script)
        self.assertIn("llmPipelineConcurrency", script)
        self.assertIn("llmPipelineGateTokens", script)
        self.assertIn("llmPipelineGateMode", script)
        self.assertIn("autoPipelineGateTokens", script)
        self.assertIn("function llmPipelineGateEdited()", script)
        self.assertIn("function llmUseAutoPipelineGate()", script)
        self.assertIn("payload.pipelineGateMode = document.getElementById('llmPipelineGateMode')", script)
        self.assertIn("if (payload.pipelineGateMode === 'manual')", script)
        self.assertIn("providerStatusLabel", script)
        self.assertIn("item.enabled === false ? 'disabled' : ''", script)
        self.assertIn("mode: custom ? 'custom' : 'preset'", script)
        self.assertIn("payload.timeoutSeconds = document.getElementById('llmProviderTimeoutSeconds')", script)
        self.assertIn("function collectLlmProviderSettingsFromModal()", script)
        self.assertIn("function saveLlmProviderModal()", script)
        self.assertIn("function testLlmProviderModal()", script)
        self.assertIn("fetch('/api/llm-provider/test'", script)
        self.assertIn("function collectLlmProviderChainFromModal()", script)
        self.assertIn("function moveLlmProviderChainEntry(index, offset)", script)
        self.assertIn("function addLlmProviderFallback()", script)
        self.assertIn("fetch('/api/llm-provider-chain/test'", script)
        self.assertIn("fetch('/api/llm-provider-chain', {method:'PUT'", script)
        self.assertIn('@router.post("/llm-provider/test")', router)
        self.assertIn('@router.get("/llm-provider-chain")', router)
        self.assertIn('@router.put("/llm-provider-chain")', router)
        self.assertIn('@router.post("/llm-provider-chain/test")', router)
        self.assertIn("run_in_threadpool(settings.test_llm_provider", router)
        self.assertIn("run_in_threadpool(settings.update_llm_provider", router)
        self.assertIn('@router.get("/settings/external-tools/catalog")', router)
        self.assertIn('@router.post("/settings/external-tools/rediscover")', router)
        self.assertIn('@router.post("/settings/external-tools/add")', router)
        self.assertIn("fetch('/api/settings/external-tools/rediscover'", script)
        self.assertIn("function renderExternalToolRediscoveryModal(data, message)", script)
        self.assertIn("function addManualExternalTool()", script)
        self.assertIn("function refreshExternalToolDiscoveryViews", script)
        self.assertIn("检测并刷新缓存", script)
        self.assertIn("tool-config-snapshot-write", ai_assets_service)
        self.assertIn("工具配置刷新失败", script)
        self.assertIn("openclaw-2", script)

    def test_msgbox_button_and_modal_are_wired(self):
        script = (ROOT / "src" / "dashboard" / "app" / "static" / "js" / "app.js").read_text(encoding="utf-8")
        html = (ROOT / "src" / "dashboard" / "app" / "static" / "index.html").read_text(encoding="utf-8")
        css = (ROOT / "src" / "dashboard" / "app" / "static" / "css" / "style.css").read_text(encoding="utf-8")
        router = (ROOT / "src" / "dashboard" / "app" / "routers" / "settings.py").read_text(encoding="utf-8")
        self.assertIn('id="msgboxButton"', html)
        self.assertIn("openMsgboxModal()", html)
        self.assertIn("fetch('/api/msgbox?limit=20')", script)
        self.assertIn("function renderMsgboxButton", script)
        self.assertIn("function openMsgboxModal", script)
        self.assertIn("function handleMsgboxApiPost", script)
        self.assertIn("function handleMsgboxActionPayload", script)
        self.assertIn("function openDashboardPage", script)
        self.assertIn("encodeURIComponent(JSON.stringify(action))", script)
        self.assertIn("action.kind === 'apiPost'", script)
        self.assertIn("setInterval(refreshMsgbox, 60000)", script)
        self.assertIn(".msgbox-button", css)
        self.assertIn('@router.get("/msgbox")', router)

    def test_history_backfill_button_modal_and_api_are_wired(self):
        script = (ROOT / "src" / "dashboard" / "app" / "static" / "js" / "app.js").read_text(encoding="utf-8")
        html = (ROOT / "src" / "dashboard" / "app" / "static" / "index.html").read_text(encoding="utf-8")
        css = (ROOT / "src" / "dashboard" / "app" / "static" / "css" / "style.css").read_text(encoding="utf-8")
        router = (ROOT / "src" / "dashboard" / "app" / "routers" / "ai_assets.py").read_text(encoding="utf-8")
        self.assertIn('id="historyBackfillButton"', html)
        self.assertIn("openHistoryBackfillModal()", html)
        self.assertIn("function openHistoryBackfillModal()", script)
        self.assertIn("function previewHistoryBackfill()", script)
        self.assertIn("function startHistoryBackfill()", script)
        self.assertIn("function historyBackfillPlanKey(payload)", script)
        self.assertIn("HISTORY_BACKFILL_LAST_PLAN_KEY !== planKey", script)
        self.assertIn("HISTORY_BACKFILL_LAST_PLAN_PAYLOAD = payload", script)
        self.assertIn("HISTORY_BACKFILL_LAST_PLAN_PAYLOAD || historyBackfillPayload(true)", script)
        self.assertIn("const payload = historyBackfillSelectedPlanPayload(overwriteDaily)", script)
        self.assertIn("HISTORY_BACKFILL_PENDING_SELECTION", script)
        self.assertIn("function historyBackfillPendingKey(item)", script)
        self.assertIn("function historyBackfillSelectedPeriodsForQueue()", script)
        self.assertIn("function toggleHistoryBackfillPendingItem(key, checked)", script)
        self.assertIn("data-history-pending-key", script)
        self.assertIn("history-backfill-task-check", script)
        self.assertIn("daily: false", script)
        self.assertIn("noQueuedHistoryItems", script)
        self.assertIn("dryRunRequiredBeforeQueue", script)
        self.assertIn("function openHistoryBackfillPeriodPicker()", script)
        self.assertIn("function confirmHistoryBackfillPeriods()", script)
        self.assertIn("fetch('/api/foundation/history-backfill'", script)
        self.assertIn("historyBackfillRunMode", script)
        self.assertIn("historyBackfillScheduledAt", script)
        self.assertIn("historyBackfillSelectedBox", script)
        self.assertIn("data-history-period-index", script)
        self.assertIn("HISTORY_BACKFILL_PICKER_PERIODS", script)
        self.assertIn("history-backfill-month-group", script)
        self.assertIn("pendingItems", script)
        self.assertIn("historyBackfillPendingType", script)
        self.assertIn("dailyPipelineDays", script)
        self.assertIn("existingDiaryDays", script)
        self.assertIn("overwriteDaily", script)
        self.assertIn("overwriteDaily: !dryRun && Boolean(overwriteDaily)", script)
        self.assertIn("覆盖式重新生成", script)
        self.assertIn("window.confirm", script)
        self.assertIn("选择周期", script)
        self.assertIn("预约生成", script)
        self.assertIn("请在后台任务查看详细进度", script)
        self.assertIn("openBackgroundTasksModal()", script)
        self.assertIn("function handleBackgroundTaskAction", script)
        self.assertIn("cancel_requested", script)
        self.assertIn("cancelled", script)
        self.assertIn("includeSummaries", script)
        self.assertIn("生成周/月总结（会覆盖当前已有周/月总结）", script)
        self.assertIn("计划预览", script)
        self.assertIn("historyBackfillInvalidatePreview", script)
        self.assertIn('disabled title="${escapeHtml(labels.dryRunRequiredBeforeQueue)}"', script)
        self.assertIn(".history-backfill-button", css)
        self.assertIn(".history-backfill-selected", css)
        self.assertIn(".history-backfill-month-group", css)
        self.assertIn(".history-backfill-week", css)
        self.assertIn(".history-backfill-plan", css)
        self.assertIn(".history-backfill-task-check", css)
        self.assertIn(".task-monitor-actions", css)
        self.assertIn('@router.post("/foundation/history-backfill")', router)
        self.assertIn('@router.post("/foundation/history-backfill/{run_id}/cancel")', router)
        self.assertIn('@router.post("/foundation/history-backfill/{run_id}/retry-failed")', router)

    def test_pipeline_background_tasks_have_flat_expandable_token_details(self):
        script = (ROOT / "src" / "dashboard" / "app" / "static" / "js" / "app.js").read_text(encoding="utf-8")
        css = (ROOT / "src" / "dashboard" / "app" / "static" / "css" / "style.css").read_text(encoding="utf-8")

        self.assertIn("function renderPipelineTaskDetails(task)", script)
        self.assertIn('class="pipeline-run-details"', script)
        self.assertIn('class="pipeline-stage-row"', script)
        self.assertIn("inputTokens", script)
        self.assertIn("cacheReadTokens", script)
        self.assertIn("reasoningTokens", script)
        self.assertIn("attempt.failureClass", script)
        self.assertIn("stage.artifactCommitted", script)
        self.assertIn("unavailable: '不可用'", script)
        self.assertIn("unavailable: 'unavailable'", script)
        self.assertIn(".pipeline-stage-row > summary", css)
        self.assertIn(".pipeline-call-row", css)
        self.assertNotIn('class="pipeline-stage-card"', script)

    def test_period_summary_renderer_supports_structured_markdown(self):
        script = (ROOT / "src" / "dashboard" / "app" / "static" / "js" / "app.js").read_text(encoding="utf-8")
        css = (ROOT / "src" / "dashboard" / "app" / "static" / "css" / "style.css").read_text(encoding="utf-8")
        self.assertIn("wrPeriodSummaryMetaHtml", script)
        self.assertIn("overviewTitles", script)
        self.assertIn("本周总结", script)
        self.assertIn("wrCleanSummaryQuoteLine", script)
        self.assertIn("一些名言", script)
        self.assertIn("cleaned.includes(quoteText)", script)
        self.assertIn("overviewTitles.includes(s.title)", script)
        self.assertIn("careTitles.includes(s.title)", script)
        self.assertIn("wr-narrative-md-title", script)
        self.assertIn("line.match(/^(\\d+)\\.\\s+(.+)$/)", script)
        self.assertIn("line.startsWith('> ')", script)
        self.assertIn(".wr-narrative-meta", css)
        self.assertIn(".wr-narrative-md-section blockquote", css)

    def test_dashboard_foundation_date_helpers_use_loaded_timezone(self):
        script = (ROOT / "src" / "dashboard" / "app" / "static" / "js" / "app.js").read_text(encoding="utf-8")
        self.assertIn("let ACTANARA_DASHBOARD_TIMEZONE", script)
        self.assertIn("function loadDashboardTimezone()", script)
        self.assertIn("ACTANARA_DASHBOARD_TIMEZONE = schedule.timezone || general.timezone", script)
        self.assertIn("timeZone: timezone", script)

    def test_nova_rag_page_exposes_rag_control_plane(self):
        script = (ROOT / "src" / "dashboard" / "app" / "static" / "js" / "app.js").read_text(encoding="utf-8")
        html = (ROOT / "src" / "dashboard" / "app" / "static" / "index.html").read_text(encoding="utf-8")
        router = (ROOT / "src" / "dashboard" / "app" / "routers" / "settings.py").read_text(encoding="utf-8")
        self.assertIn('id="ragSearchSettings"', html)
        self.assertIn("nova-RAG", html)
        self.assertNotIn("data-tab=\"rag\"", script)
        self.assertNotIn("id=\"setRagMode\"", script)
        self.assertNotIn("id=\"setRagEmbeddingProvider\"", script)
        self.assertIn('id="ragPowerBtn"', html)
        self.assertIn("初始化 nova-RAG", script)
        self.assertIn("停用 nova-RAG", script)
        self.assertIn("toggleNovaRagPower()", script)
        self.assertIn("变更请走“迁移RAG基座/模式”", script)
        self.assertIn("saveRagSettingsPanel()", script)
        self.assertIn("NOVA_RAG_EMBEDDING_MODELS", script)
        self.assertIn("BAAI/bge-large-zh-v1.5", script)
        self.assertIn("intfloat/multilingual-e5-small", script)
        self.assertIn("BAAI/bge-large-en-v1.5", script)
        self.assertIn("all-MiniLM-L6-v2", script)
        self.assertIn("updateRagMigrationModelOptions()", script)
        self.assertIn("updateRagMigrationDimensionFromModel()", script)
        self.assertIn("updateRagMigrationFieldVisibility()", script)
        self.assertIn("ragMigrationApiKeyEnvRow", script)
        self.assertIn("ragMigrationConfirmationRow", script)
        self.assertIn("const confirmationText = payload.confirmationText", script)
        self.assertIn("JSON.stringify({initMode, confirmationText, autoPromote: initMode, targetProfile})", script)
        self.assertNotIn("const confirmationText = initMode ? 'MIGRATE RAG PROFILE'", script)
        self.assertIn("fetch('/api/rag/settings'", script)
        self.assertIn("enabledNovaRagSettingsPayload()", script)
        collect_rag_body = script.split("function collectRagSettingsFromModal()", 1)[1].split("async function ragOperatorAction", 1)[0]
        enable_rag_body = script.split("function enabledNovaRagSettingsPayload()", 1)[1].split("async function enableNovaRagServices", 1)[0]
        self.assertNotIn("languageProfile:", collect_rag_body)
        self.assertNotIn("languageProfile:", enable_rag_body)
        self.assertIn("targetProfile: {mode, providerId, model, dimension, endpoint, apiKeyEnv, languageProfile}", script)
        self.assertIn("delete disabledPayload.languageProfile", script)
        self.assertIn("indexing: {", script)
        self.assertNotIn("id=\"setRagLegacyIndex\"", script)
        self.assertNotIn("'v2-shadow','v2'", script)
        self.assertNotIn("id=\"setRagModel\"", script)
        self.assertNotIn("id=\"setRagDimension\"", script)
        self.assertNotIn("id=\"setRagServerPort\"", script)
        self.assertNotIn("id=\"setRagServerEnabled\"", script)
        self.assertNotIn("id=\"setRagEnabled\"", script)
        self.assertNotIn("id=\"setRagLanguage\"", script)
        self.assertIn("即时参数", script)
        self.assertIn("ragProfileLabel(profile)", script)
        self.assertIn("providerId", script)
        self.assertNotIn("id=\"setRagEndpoint\"", script)
        self.assertNotIn("id=\"setRagApiKeyEnv\"", script)
        self.assertNotIn("id=\"setRagSecretBackend\"", script)
        self.assertIn('id="setRagCloudProviderCredential" type="password" autocomplete="new-password"', script)
        self.assertIn("['api' + 'Key']: cloudProviderCredential", collect_rag_body)
        self.assertIn("delete rag.embedding.apiKey", script)
        self.assertNotIn("id=\"setRagSecretService\"", script)
        self.assertNotIn("id=\"setRagSecretAccount\"", script)
        self.assertIn("refreshRagStatus()", script)
        self.assertIn("loadRagSearchCoverage()", script)
        self.assertIn("loadRagEval()", script)
        self.assertIn("openRagProfileMigrationModal(options)", script)
        self.assertIn("迁移RAG基座/模式", script)
        self.assertIn("previewRagProfileMigration()", script)
        self.assertIn("fetch('/api/rag/profile/migrate/plan'", script)
        self.assertIn("INITIALIZE ACTANARA RAG", script)
        self.assertIn("initializationConfirmationMismatch", script)
        self.assertIn("openRagExternalSkillRegistration()", script)
        self.assertIn("fetch('/api/rag/profile/migrate'", script)
        self.assertIn('@router.post("/rag/profile/migrate/plan")', router)
        self.assertIn("fetch('/api/settings/external-tools/rag-skill-registration/plan'", script)
        self.assertIn("fetch('/api/settings/external-tools/rag-skill-registration'", script)
        self.assertIn("status.productEnabled !== false", script)
        self.assertIn("status.disabledReason", script)
        self.assertNotIn("id=\"ragSearchSection\"", script)
        self.assertIn("fetch('/api/rag/status?probe=true')", script)
        self.assertIn("fetch('/api/rag/search'", script)

    def test_tasks_sse_reuses_nova_task_enabled_gate(self):
        router = (ROOT / "src" / "dashboard" / "app" / "routers" / "ai_assets.py").read_text(encoding="utf-8")
        sse_body = router.split("async def sse_tasks", 1)[1].split("return StreamingResponse", 1)[0]
        self.assertIn("nova_task_review.task_board_payload", sse_body)
        self.assertIn("foundation.nova_task_enabled()", sse_body)
        self.assertNotIn('"novaTaskEnabled": True', sse_body)

    def test_dashboard_exposes_primary_rag_search_page(self):
        html = (ROOT / "src" / "dashboard" / "app" / "static" / "index.html").read_text(encoding="utf-8")
        script = (ROOT / "src" / "dashboard" / "app" / "static" / "js" / "app.js").read_text(encoding="utf-8")
        self.assertIn("showPage('rag-search'", html)
        self.assertIn('id="page-rag-search"', html)
        self.assertIn('id="ragPageSearchQuery"', html)
        self.assertIn('id="ragProfileMigrateBtn"', html)
        self.assertIn("迁移RAG基座/模式", html)
        self.assertIn('id="ragExternalSkillBtn"', html)
        self.assertIn('runRagProductionSync()', html)
        self.assertIn('openBackgroundTasksModal()', html)
        self.assertIn("loadRagSearchPage()", script)
        self.assertIn("runRagPageSearch()", script)
        self.assertIn("function runRagProductionSync()", script)
        self.assertIn("SYNC ACTANARA RAG", script)
        self.assertIn("RAG_PRODUCTION_SYNC_BUSY", script)
        self.assertIn("productionSyncConfirmationPrompt", script)
        self.assertIn("fetch('/api/rag/sync/run'", script)
        self.assertIn("dateCoverage.onlyMissingRagIndexDates", script)
        self.assertIn("function compactIsoDateRanges(values)", script)
        self.assertIn("missingRagRanges = compactIsoDateRanges(allMissingRagDates)", script)
        self.assertIn("t.ragIndexDateRanges + missingRagRanges.join(', ')", script)
        self.assertIn("t.upstreamDateRanges + missingUpstreamRanges.join(', ')", script)
        self.assertIn("missingRagDates.length ? '<button type=\"button\" class=\"wr-export-btn\" onclick=\"runRagProductionSync()\"", script)
        self.assertIn("missingUpstreamDates.length ? '<button type=\"button\" class=\"wr-export-btn\" onclick=\"openHistoryBackfillModal()\"", script)
        self.assertIn("onclick=\"showPage(\\'foundation-ops\\')\"", script)
        self.assertIn("function closeRagSearchCoverage()", script)
        self.assertIn("window._lastRagSearchStatus = data", script)
        self.assertIn("fetch('/api/rag/status?probe=true')", script)
        self.assertIn("fetch('/api/rag/search'", script)
        self.assertIn("autoPromote: initMode", script)
        self.assertIn("submitBtn.disabled = true", script)
        self.assertIn("初始化会保存 nova-RAG 配置，在后台生成 v2 candidate index，并在成功后自动 promote", script)
        service = (ROOT / "src" / "dashboard" / "app" / "services" / "settings.py").read_text(encoding="utf-8")
        self.assertNotIn("_ensure_rag_launch_agent_registered", service)

    def test_rag_external_agent_contract_is_read_only(self):
        router = (ROOT / "src" / "dashboard" / "app" / "routers" / "settings.py").read_text(encoding="utf-8")
        service = (ROOT / "src" / "dashboard" / "app" / "services" / "settings.py").read_text(encoding="utf-8")
        server = (ROOT / "src" / "agentic_rag" / "embedding_server.py").read_text(encoding="utf-8")
        self.assertIn('@router.get("/rag/external/health")', router)
        self.assertIn('@router.get("/rag/external/stats")', router)
        self.assertIn('@router.post("/rag/external/search")', router)
        self.assertIn('@router.get("/rag/coverage")', router)
        self.assertIn('@router.get("/rag/eval/latest")', router)
        self.assertIn('@router.get("/rag/external/contract")', router)
        self.assertIn('@router.get("/settings/external-tools/rag-skill-registration/plan")', router)
        self.assertIn('@router.post("/settings/external-tools/rag-skill-registration")', router)
        self.assertIn('@router.get("/settings/external-tools/rag-skill-registration/jobs")', router)
        self.assertIn('@router.post("/rag/external/index/run")', router)
        self.assertIn('@router.put("/rag/external/settings")', router)
        self.assertIn('"mutationAllowed": False', service)
        self.assertIn('"version": 2', service)
        self.assertIn('"provider": status.get("provider") or {}', service)
        self.assertIn("usagePrompt", service)
        self.assertIn('status_code=403', router)
        self.assertIn('@app.get("/stats")', server)
        self.assertIn('@app.post("/memory/write")', server)
        self.assertIn('@app.post("/index/run")', server)
        self.assertIn('rag-external-api-read-only', server)

    def test_rag_server_query_embedding_uses_provider_boundary(self):
        server = (ROOT / "src" / "agentic_rag" / "embedding_server.py").read_text(encoding="utf-8")
        provider = (ROOT / "src" / "agentic_rag" / "query_embedding_provider.py").read_text(encoding="utf-8")
        sync = (ROOT / "src" / "agentic_rag" / "rag_v2_sync.py").read_text(encoding="utf-8")
        self.assertIn("create_query_embedding_provider_from_config", server)
        self.assertIn("await loop.run_in_executor(_inference_executor, embedding_provider.load)", server)
        self.assertIn('"status": "ok" if _embedding_provider_ready() else "booting"', server)
        self.assertIn("_encode_queries([baseline_query]", server)
        self.assertIn("_dense_scores_for_embedding", server)
        self.assertNotIn("from sentence_transformers import SentenceTransformer", server)
        self.assertIn("timeout_seconds: float = 600.0", sync)
        self.assertIn("class LocalQueryEmbeddingProvider", provider)
        self.assertIn("class CloudQueryEmbeddingProvider", provider)
        self.assertIn("def create_query_embedding_provider_from_config", provider)
        self.assertIn("def encode_query", provider)
        self.assertIn("from sentence_transformers import SentenceTransformer", provider)

    def test_dashboard_markdown_and_fetch_security_contracts(self):
        script = (ROOT / "src" / "dashboard" / "app" / "static" / "js" / "app.js").read_text(encoding="utf-8")
        tasks_html = (ROOT / "src" / "dashboard" / "app" / "static" / "tasks.html").read_text(encoding="utf-8")

        self.assertIn("const ACTANARA_CSRF_HEADER = 'X-Actanara-CSRF'", script)
        self.assertIn("window.fetch = function(input, init)", script)
        self.assertIn("function sanitizeDashboardHtml", script)
        self.assertIn("function renderSafeMarkdown", script)
        self.assertIn("marked.parse(text)", script)
        self.assertIn("return sanitizeDashboardHtml(html)", script)
        self.assertIn("${renderSafeMarkdown(d.rawContent)}", script)
        self.assertNotIn("${marked.parse(d.rawContent)}", script)
        self.assertIn("const csrfHeader = 'X-Actanara-CSRF'", tasks_html)
        self.assertIn("window.fetch = function(input, init)", tasks_html)


if __name__ == "__main__":
    unittest.main()
